apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myapp=jibeshshrestha/web-local
    argocd-image-updater.argoproj.io/myapp.update-strategy: semver
    argocd-image-updater.argoproj.io/myapp.ignore-tags: latest, dev
    argocd-image-updater.argoproj.io/myapp.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/myapp.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
spec:
  project: default

  source:
    repoURL: https://github.com/JavaIsNotHard/demo-helmchart
    targetRevision: main
    path: .
    helm:
      valueFiles:
      - values.yaml
      - values/dev.yaml
      values: |
        imagePullSecrets: []

  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
